/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantalla;

import Clases.CajaValidacion;
import Clases.Operacion;

/**
 *
 * @author mco_a
 */
public class Calculadora extends javax.swing.JFrame {

    CajaValidacion valor1;
    CajaValidacion valor2;
    CajaValidacion resultado;
    Operacion opera;
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        
        valor1 = new CajaValidacion(txtNum1, lblError1);
        valor2 = new CajaValidacion(txtNum2, lblError2);
        resultado = new CajaValidacion(txtResultado, lblError3);
        
        opera = new Operacion(valor1, valor2, resultado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        lblBarra = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        txtNum1 = new javax.swing.JTextField();
        txtNum2 = new javax.swing.JTextField();
        lblNum2 = new javax.swing.JLabel();
        lblNum1 = new javax.swing.JLabel();
        lblError3 = new javax.swing.JLabel();
        lblError2 = new javax.swing.JLabel();
        lblError1 = new javax.swing.JLabel();
        btnSuma = new javax.swing.JLabel();
        btnDivisión = new javax.swing.JLabel();
        btnMultiplicación = new javax.swing.JLabel();
        btnResta = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/Close.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 0, -1, -1));

        lblBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/Barra.png"))); // NOI18N
        lblBarra.setText("Basic Calculator");
        lblBarra.setToolTipText("");
        lblBarra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/btnLimpiar.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnClearMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnClearMouseReleased(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 428, -1, -1));

        txtResultado.setEditable(false);
        txtResultado.setBackground(new java.awt.Color(41, 46, 55));
        txtResultado.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(255, 255, 255));
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResultado.setBorder(null);
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 288, 100));

        txtNum1.setBackground(new java.awt.Color(47, 55, 71));
        txtNum1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNum1.setForeground(new java.awt.Color(255, 255, 255));
        txtNum1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNum1.setBorder(null);
        jPanel1.add(txtNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 288, 40));

        txtNum2.setBackground(new java.awt.Color(47, 55, 71));
        txtNum2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNum2.setForeground(new java.awt.Color(255, 255, 255));
        txtNum2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNum2.setBorder(null);
        jPanel1.add(txtNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 288, 40));

        lblNum2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNum2.setForeground(new java.awt.Color(0, 204, 204));
        lblNum2.setText("Num2:");
        jPanel1.add(lblNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        lblNum1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNum1.setForeground(new java.awt.Color(0, 204, 204));
        lblNum1.setText("Num1:");
        jPanel1.add(lblNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        lblError3.setForeground(new java.awt.Color(255, 153, 51));
        jPanel1.add(lblError3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 288, 20));

        lblError2.setForeground(new java.awt.Color(255, 153, 51));
        jPanel1.add(lblError2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 288, 20));

        lblError1.setForeground(new java.awt.Color(255, 153, 51));
        jPanel1.add(lblError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 288, 20));

        btnSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/btnSuma.png"))); // NOI18N
        btnSuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSumaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSumaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSumaMouseReleased(evt);
            }
        });
        jPanel1.add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 355, -1, -1));

        btnDivisión.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/btnDivisión.png"))); // NOI18N
        btnDivisión.setPreferredSize(new java.awt.Dimension(69, 70));
        btnDivisión.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDivisiónMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDivisiónMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDivisiónMouseReleased(evt);
            }
        });
        jPanel1.add(btnDivisión, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 355, -1, -1));

        btnMultiplicación.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/btnMultiplicación.png"))); // NOI18N
        btnMultiplicación.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMultiplicaciónMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMultiplicaciónMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMultiplicaciónMouseReleased(evt);
            }
        });
        jPanel1.add(btnMultiplicación, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 355, -1, -1));

        btnResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/btnResta.png"))); // NOI18N
        btnResta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRestaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRestaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRestaMouseReleased(evt);
            }
        });
        jPanel1.add(btnResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 355, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/Fondo.png"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 288, 498));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSumaMouseClicked
        opera.Suma();
    }//GEN-LAST:event_btnSumaMouseClicked

    private void btnSumaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSumaMousePressed
        btnSuma.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/IMGS/+.png"))
        );
    }//GEN-LAST:event_btnSumaMousePressed

    private void btnSumaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSumaMouseReleased
        btnSuma.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/IMGS/btnSuma.png"))
        );
    }//GEN-LAST:event_btnSumaMouseReleased

    private void btnRestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaMouseClicked
        opera.Resta();
    }//GEN-LAST:event_btnRestaMouseClicked

    private void btnRestaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaMousePressed
        btnResta.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/IMGS/-.png"))
        );
    }//GEN-LAST:event_btnRestaMousePressed

    private void btnRestaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestaMouseReleased
        btnResta.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/IMGS/btnResta.png"))
        );
    }//GEN-LAST:event_btnRestaMouseReleased

    private void btnMultiplicaciónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplicaciónMouseClicked
        opera.Multiplicacion();
    }//GEN-LAST:event_btnMultiplicaciónMouseClicked

    private void btnMultiplicaciónMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplicaciónMousePressed
         btnMultiplicación.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/IMGS/x.png"))
        );
    }//GEN-LAST:event_btnMultiplicaciónMousePressed

    private void btnMultiplicaciónMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplicaciónMouseReleased
        btnMultiplicación.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/IMGS/btnMultiplicación.png"))
        );
    }//GEN-LAST:event_btnMultiplicaciónMouseReleased

    private void btnDivisiónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivisiónMouseClicked
        opera.Division();
    }//GEN-LAST:event_btnDivisiónMouseClicked

    private void btnDivisiónMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivisiónMousePressed
        btnDivisión.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/IMGS/÷.png"))
        );
    }//GEN-LAST:event_btnDivisiónMousePressed

    private void btnDivisiónMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivisiónMouseReleased
        btnDivisión.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/IMGS/btnDivisión.png"))
        );
    }//GEN-LAST:event_btnDivisiónMouseReleased

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        txtNum1.setText("");
        txtNum2.setText("");
        txtResultado.setText("");
        lblError3.setText("");
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnClearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMousePressed
        btnClear.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/IMGS/AllClear.png"))
        );
    }//GEN-LAST:event_btnClearMousePressed

    private void btnClearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseReleased
        btnClear.setIcon(new javax.swing.ImageIcon(
                getClass().getResource(
                        "/IMGS/btnLimpiar.png"))
        );
    }//GEN-LAST:event_btnClearMouseReleased

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnDivisión;
    private javax.swing.JLabel btnMultiplicación;
    private javax.swing.JLabel btnResta;
    private javax.swing.JLabel btnSuma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBarra;
    private javax.swing.JLabel lblError1;
    private javax.swing.JLabel lblError2;
    private javax.swing.JLabel lblError3;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNum1;
    private javax.swing.JLabel lblNum2;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
